spring: 
  rabbitmq:
    port: 5672
    username: melodykke
    password: Y223183q!
    host: localhost
zuul:
  sensitive-headers: 
  routes:
#    myProduct:
#      path: /myProduct/**
#      serviceId: product
    product: /my-product/**
  ignored-patterns:
       - /**/product/listForOrder
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.bus: debug
