
spring:
  application:
    name: api-gateway
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config
      profile: dev
zuul:
  routes:
#    myProduct:
#      path: /myProduct/**
#      serviceId: product
    product: /myProduct/**
  ignored-patterns:
       - /**/product/listForOrder
management:
  endpoints:
    web:
      exposure:
        include: "*"
